config/routes.rb
Mc101::Application.routes.draw do

  root to: 'static_pages#home'

  get '/lessons', to: 'static_pages#lessons'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, 
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def lessons
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30146767-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
        <div class="container">
			<%= link_to "mlc101", root_path, id: "logo" %>
				<ul class="nav pull-right">
					<li><%= link_to "Home",    		root_path %></li>
					<li><%= link_to "About Us",    	about_path %></li>
					<li><%= link_to "Lessons",  	lessons_path %></li>
						<li>
						<% if user_signed_in? %>
							<li>Signed in as <%= current_user.email %></li>
							<li>Not you? <%= link_to "Sign out", destroy_user_session_path %></li>
						<% else %>
							<li><% link_to "Sign up", new_user_registration_path %> or <% link_to "Sign in", new_user_session_path %></li>
						<% end %>
						</li>
				</ul>		
        </div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mandarin Chinese Lessons 101 - Introductory Chinese | Home</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/analytics' %>
  <meta name="google-site-verification" content="kmXqGLcYYCPi8g0WqvOrwLMqZAnYKGA9uHY-bccnAA0" />
</head>

<body>
<p>adding a bit of txt in here to see if things are uploading properly</p>
<%= render 'layouts/header' %>

	
	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>
	
<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/static_pages/about.html.erb
<div class="container" style="h2:align-left">
	<div class="row">
		<div class = "span12">
			<h1>About Us</h1>
		</div>
	</div>
	<div class="row">
		<div class = "span12">
			<h2>What is Mandarin Chinese Lessons 101?</h2>
			<p>MLC101 is a revolutionary way to learn Mandarin Chinese. We believe that the way to learn a language is by speaking it. However, you'll never learn how to speak a language in a classroom, from a textbook, or even from an online program like MLC101.
			Anyway who says that you can is probably uninformed, or trying to sell you an overpriced language course. What we can do here with our online program is give you a basis for speaking. Hence 101 - introductory.
			If you show up in Shanghai or Taipei without any lessons whatsoever, you'll be in over your head. So get a basis. Learn enough here so that you can function, tell some stories, and make some friends.
			Then when you arrive in China, Singapore, or wherever else you're headed, you'll already be partway there. But don't just take my word for it. Check out our first couple of lessons totally free of charge. 
			You don't even have to put in your email address. If you like what you see there and you want to continue with our program, then you can buy the rest of the program for $9.95. 
			It may seem expensive for website access, but consider it in perspective. That's considerably lower than you would pay for a 60-minute chinese lesson, and about 10% of the price you would
			pay for a introductory Mandarin college textbook.</p></br>
		</div>
	</div>
	<div class="row">
		<div class = "span12">
			<h1>Frequently Asked Questions</h1>
		</div>
	</div>
	<div class="row">
		<div class = "span12">
			<h2>What makes the MLC101 system the best way to learn Chinese?</h2>
			
			<p><b>Sentence-Based Learning</b></p>
			<p>Classroom language learning focuses on grammar rules and vocabulary. Which is great if you need to take a test, but not so great if you actually want to learn to speak the language. Our unique system focuses instead on sentences, bringing in grammar and new vocabulary as you need to learn them.</p>
			
			<p><b>Perfect Pronunciation</b></p>
			</p>Every single word and sentence in our course has been recorded by a native speaker, so you'll know exactly how it should sound when you say it. You can even choose which gender you would prefer to imitate!</p>
			
			<p><b>Contextual Learning</b></p>
			<p>Our lessons are broken up into semantic, context-driven modules. So you'll know exactly what to say at the bank, at dinner, and to the cute girl or guy sitting at the end of the bar.</p>
			
			<p><b>Effective Vocabulary Improvement</b></p>
			<p>No more flashcards! Because you're learning everything in context, you won't need to study vocabulary. We'll give you the tools you need to incorporate new words into your daily vocabulary as soon as you learn them, cementing them for good.</p>
			</br>
			<p>Find out for yourself how MLC101 is the <i> most effective way to learn.</i> Start today with our <%= link_to "free introductory lessons!", lessons_path%></p>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<div class="container">
	<div class="center hero-unit">
		<h1>Welcome to Mandarin Chinese Lessons 101</h1>
		<h2>Its time to revolutionize the teaching of Chinese
		as a foreign language</h2>
		
		<%= link_to "Get Started!", '#', class: "btn btn-large btn-primary" %>
		<%= link_to "What do we do?", about_path, class: "btn btn-large btn-primary" %>
	</div>
</div>	

app/views/static_pages/lessons.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span3">
			<h2>Lessons</h2>
			<ul>
				<li><%= link_to "Lesson 0 - Pinyin and Pronunciation", "#" %></li></br>
				<li><%= link_to "Lesson 1 - The Basics - Nouns, Verbs, and Syntax", "#" %></li></br>
				<li><%= link_to "Lesson 2 - Time and Place in Chinese", "#" %></li></br>
				<li><%= link_to "Lesson 3 - Your First Real Conversation", "#" %></li></br>
				<li><%= link_to "Lesson 4 - At the Restaurant", "#" %></li></br>
				<li><%= link_to "Lesson 5 - At the Market", "#" %></li></br>
				<li><%= link_to "Lesson 6 - Public Transportation and Taxis", "#" %></li></br>
			</ul>
		</div>
		<div class="span9">
			<h2>This is where the first lesson will go</h2>
		</div>
	</div>
</div>